### ISSUE TITLE
Node Red Version

### ISSUE THREAD

**Issue by andesse** [yadomi/node-red-contrib-philipshue-events#14]
Hi friend, 
is it possible to run this Contrib on NodeRed 1.2.9?
There is an NodeRed Addon that isnt maintained and it  still runs on 1.2.9
Quite a lot of people use it in Germany. I tried to install today,it failed for the reason that your contrib needs 2.x something

Can you lower the Version that is needed for this contrib, or has your contrib a dependence from higher NodeRed Versions?

Greetings
Andreas

**Comment by yadomi** [comment]
Hello, this node only has one dependency, it's [eventsource](https://www.npmjs.com/package/eventsource) and it needs node >= 12 since v2.0.0 (see [HISTORY.md](https://github.com/EventSource/eventsource/blob/master/HISTORY.md#200))

The issue is that node-red below < 2 may not have the correct version of node. 

See: https://nodered.org/blog/2021/07/20/version-2-0-released#nodejs-12-or-later-required

**Comment by yadomi** [comment]
For instance, the docker image of node-red@1.2.9 use node v10.23.2, which would not satisfy npm / dependencies.

https://hub.docker.com/layers/node-red/nodered/node-red/1.2.9/images/sha256-13a053d1b2c6340ec8bed9a3ff2a7b799f5cfcf7560d84a2e0da67e3b089ecaa?context=explore

**Comment by andesse** [comment]
Ok, thanks for clarifying.

I used this Addon Redmatic before and the developer is even more lazy than the HueMagic one. So annoying. Built a separate Tinkerboard 2S setup for this reason to run NodeRed on its own.

Thanks Yadomi, your contrib saved quite a lot of men from getting divorced, legend. 

Cheers 
Andreas
