### ISSUE TITLE
Short question: why node-red >=2.2.2 ?

### ISSUE THREAD

**Issue by windkh** [yadomi/node-red-contrib-philipshue-events#17]
First, thanks for your great work.

Your package.json contains the following limitation
"node-red": {
    "version": ">=2.2.2",

Is there any 2.2.2 specific feature that you use in your nodes  or why do you need that? Could it be >2.0.0, too?

**Comment by yadomi** [comment]
Hi, 

the node mostly based on the [eventsource](https://www.npmjs.com/package/eventsource) package that only require Node 12 (see: https://github.com/EventSource/eventsource/blob/master/package.json#L49) and Node 12 is required since NodeRED 2.0.0. 

The node don't use any specific 2.2.2 feature, so I guess it should work. I'll do some testing ASAP and release a version that change the limitation if everything works properly

**Comment by windkh** [comment]
Thanks

**Comment by andesse** [comment]
@yadomi wow, thanks for adding my flow friend! 🙏🏻

**Comment by yadomi** [comment]
@windkh I've publised version [v1.5.2](https://www.npmjs.com/package/@yadomi/node-red-contrib-philipshue-events) that should work with NodeRED >= 2.0.0
