### ISSUE TITLE
Deploying multiple times breaks the payload

### ISSUE THREAD

**Issue by sockless-coding** [yadomi/node-red-contrib-philipshue-events#4]
Deploying the flow multiple times breaks the payload object, instead of returning an actual JSON object it returns `[object Object]`.
The only way I managed to get it to work again is to reload node-red.

**Comment by yadomi** [comment]
Thanks for the report, I encountered this error as well. I think it's because I'm not handling the disconnect of the EventSource correctly. 

I'll look at this soon

**Comment by yadomi** [comment]
@sockless-coding do you still encounter the issue ? Connection errors should now be handled (see https://github.com/yadomi/node-red-contrib-philipshue-events/commit/8a60417bff5e21ef1ffcdb1b3a7f37e70855d5fe, since [v1.2.0](https://github.com/yadomi/node-red-contrib-philipshue-events/releases/tag/v1.2.0)), but there may be some edge case that I didn't catch yet.

**Comment by yadomi** [comment]
I'm closing since I've no longer encountered the issue since 1.2.0. Feel free to reopen if you have the issue again
